### ISSUE TITLE
Package 'aurelius' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [terrytangyuan/ctv-model-deployment#11]
Package [aurelius](https://CRAN.R-project.org/package=aurelius) is currently listed in CRAN Task View [ModelDeployment](https://CRAN.R-project.org/view=ModelDeployment) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by terrytangyuan** [comment]
@coatless Would you like to take a look?

**Comment by coatless** [comment]
@terrytangyuan sure!

**Comment by coatless** [comment]
Glancing at the GitHub mirror of CRAN, the package authors have been absent since ~2017. 

<https://github.com/cran/aurelius>

The offending error seems to be triggered by a routing dispatch:

https://github.com/cran/aurelius/blob/7e6899cc14dc40f44f633f73f0611325fb0b0531/R/converters.R#L108

Likely due to a change in [R 4.2.0](https://cran.r-project.org/doc/manuals/r-release/NEWS.pdf):

> Calling if() or while() with a condition of length greater than one
gives an error rather than a warning. Consequently, environment variable
_R_CHECK_LENGTH_1_CONDITION_ no longer has any effect.

So, I'll vote to remove the package from the task view as it is likely orphaned.

**Comment by terrytangyuan** [comment]
Sounds good
